
export const GIT_CURRICULUM: any = {
    'DIC1': [
        { code: 'DEV15011', title: 'Administration Systèmes', cm: 12, td: 8, tp: 8, credits: 2, status: 'Terminé', hoursDone: 28 },
        { code: 'DEV15012', title: 'Programmation Orientée Objet (POO Java)', cm: 12, td: 8, tp: 8, credits: 2, status: 'Terminé', hoursDone: 28 },
        { code: 'IHM15021', title: 'UX Design (Javascript avancé)', cm: 18, td: 12, tp: 12, credits: 3, status: 'En cours', hoursDone: 27 },
        { code: 'IHM15022', title: 'Développement Web 2 (Spring Boot)', cm: 18, td: 12, tp: 12, credits: 3, status: 'En cours', hoursDone: 16 },
        { code: 'MOD15031', title: 'ACSI 2 (UML, Design Patterns)', cm: 12, td: 8, tp: 8, credits: 2, status: 'En cours', hoursDone: 4 },
        { code: 'MOD15032', title: 'Gestion Projet IT 1 (Agilité, CI/CD, Tests)', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'IDD15041', title: 'Fondamentaux BD (+Programmation SQL)', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'IDD15042', title: 'BD NoSQL (+XML&JSON&RDF)', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'TEL15051', title: 'Traitement du Signal', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'TEL15052', title: 'Transmission de données', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'HUM15061', title: 'Techniques de communication en Français', cm: 10, td: 10, tp: 0, credits: 1, status: 'Terminé', hoursDone: 20 },
        { code: 'HUM15062', title: 'Techniques de communication en Anglais 1', cm: 10, td: 10, tp: 0, credits: 1, status: 'Terminé', hoursDone: 20 },
        { code: 'HUM15063', title: 'Management de projets 1 (Initiation)', cm: 10, td: 10, tp: 0, credits: 1, status: 'Terminé', hoursDone: 20 },
        { code: 'HUM15064', title: 'Sport', cm: 20, td: 0, tp: 0, credits: 1, status: 'En cours', hoursDone: 10 },
        { code: 'MTH16071', title: 'Recherche opérationnelle', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'MTH16072', title: 'Complexité Algorithmique', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'MTH16073', title: 'Modélisation stochastiques', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'INA16081', title: 'Introduction à l\'IA (vue panoramique)', cm: 12, td: 8, tp: 0, credits: 1, status: 'Non démarré', hoursDone: 0 },
        { code: 'INA16082', title: 'Apprentissage Automatique (Machine Learning)', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES16091', title: 'Systèmes Embarqués (Introduction)', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES16092', title: 'Fondamentaux Réseaux Informatiques', cm: 16, td: 8, tp: 16, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ16101', title: 'Immersion en Entreprise 1 (4 mois max)', cm: 0, td: 0, tp: 0, credits: 8, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ16102', title: 'Projet Transversal I + Séminaires', cm: 0, td: 0, tp: 0, credits: 4, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ16104', title: 'PPP 1', cm: 20, td: 0, tp: 0, credits: 1, status: 'Non démarré', hoursDone: 0 }
    ],
    'DIC2': [
        { code: 'DEV21011', title: 'Développement mobile et Services Web', cm: 18, td: 12, tp: 12, credits: 3, status: 'En cours', hoursDone: 32 },
        { code: 'DEV21012', title: 'DevOps (Conteneurisation et orchestration)', cm: 12, td: 8, tp: 8, credits: 2, status: 'En cours', hoursDone: 14 },
        { code: 'DEV21013', title: 'Introduction Cloud', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'DEV21014', title: 'Développement Web 3 (JEE)', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'MOD21021', title: 'Architectures logicielles', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'MOD21022', title: 'Modélisation Mathématique et Numérique', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES21031', title: 'Réseaux Informatiques Avancés (Routing, Switching)', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES21032', title: 'Protocoles IoT', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'TEL21041', title: 'Réseaux mobiles et Services', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'TEL21042', title: 'Téléphonie (RTC, ToIP)', cm: 9, td: 6, tp: 6, credits: 1.5, status: 'Non démarré', hoursDone: 0 },
        { code: 'TEL21043', title: 'Télécoms de base (Commutation, multiplexage)', cm: 9, td: 6, tp: 6, credits: 1.5, status: 'Non démarré', hoursDone: 0 },
        { code: 'HUM21051', title: 'Techniques de communication en Anglais 2', cm: 12, td: 16, tp: 0, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'HUM21052', title: 'Droit (travail, contrat, Régulation des TIC)', cm: 10, td: 10, tp: 0, credits: 1, status: 'Non démarré', hoursDone: 0 },
        { code: 'HUM21053', title: 'Management de projets 2 (Consolidation)', cm: 10, td: 10, tp: 0, credits: 1, status: 'Non démarré', hoursDone: 0 },
        { code: 'IDD22061', title: 'BD Réparties', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'IDD22062', title: 'Fondamentaux Big Data et Applications', cm: 24, td: 16, tp: 16, credits: 4, status: 'Non démarré', hoursDone: 0 },
        { code: 'IDD22063', title: 'Sécurité et Administration de Bases de Données', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'INA22071', title: 'Cryptographie et Sécurité Informatique', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'INA22072', title: 'Apprentissage Approfondie (Deep Learning)', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'INA22073', title: 'Traitement d\'image et Vision par ordinateur', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ21081', title: 'Immersion en Entreprise 2 (5 mois max)', cm: 0, td: 0, tp: 0, credits: 9, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ21082', title: 'Projet Transversal 2 + Séminaires', cm: 0, td: 0, tp: 0, credits: 4, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ21084', title: 'PPP 2', cm: 20, td: 0, tp: 0, credits: 1, status: 'Non démarré', hoursDone: 0 }
    ],
    'DIC3': [
        { code: 'DEV23011', title: 'Conception Applications Cloud Native', cm: 12, td: 8, tp: 8, credits: 2, status: 'En cours', hoursDone: 25 },
        { code: 'DEV23012', title: 'Conduite de Projet Développement Full Stack', cm: 10, td: 4, tp: 0, credits: 1, status: 'En cours', hoursDone: 4 },
        { code: 'TDD23021', title: 'Traitement de Données Textuelles (NLP&ML&NLU)', cm: 12, td: 8, tp: 8, credits: 2, status: 'En cours', hoursDone: 21 },
        { code: 'TDD23022', title: 'Technologies ML&DL et MLOps', cm: 12, td: 8, tp: 8, credits: 2, status: 'En cours', hoursDone: 12 },
        { code: 'MOD23031', title: 'Gouvernance des données', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'MOD23033', title: 'Science Décisionnelle (BI, Lac de Données)', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'IDD23041', title: 'IA Agentique (LLM, IA Générative, RAG, MCP)', cm: 12, td: 8, tp: 8, credits: 2, status: 'Terminé', hoursDone: 28 },
        { code: 'IDD23042', title: 'Technologies Blockchain', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'IDD23043', title: 'Ethique de l\'IA', cm: 10, td: 4, tp: 0, credits: 1, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES23051', title: 'Déploiement Applications Cloud', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES23052', title: 'Services et Sécurité Réseaux Informatiques', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES23053', title: 'Gouvernance des SI', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'RES23054', title: 'Cybersécurité (Gouvernance, Référentiels)', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'HUM23061', title: 'Techniques de communication en Anglais 3', cm: 18, td: 12, tp: 12, credits: 3, status: 'Non démarré', hoursDone: 0 },
        { code: 'HUM23062', title: 'Management de projets 3 (Réalisation)', cm: 12, td: 8, tp: 8, credits: 2, status: 'Non démarré', hoursDone: 0 },
        { code: 'HUM23063', title: 'Méthodologie de Recherche', cm: 10, td: 4, tp: 0, credits: 1, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ24071', title: 'Immersion en Entreprise (6 mois max)', cm: 0, td: 0, tp: 0, credits: 15, status: 'Non démarré', hoursDone: 0 },
        { code: 'SPJ24072', title: 'Projet de Fin d\'Etudes (PFE)', cm: 0, td: 0, tp: 0, credits: 15, status: 'Non démarré', hoursDone: 0 }
    ]
};
